services:
  ultra.hotels.web:
    image: ultra.hotels.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - .:/app
    environment:
      - ANGULAR_APP_API_URL=http://ultra.hotels.api:5000