/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--ds-primary-color))',
          50: 'rgb(var(--ds-primary-color-50))',
          100: 'rgb(var(--ds-primary-color-100))',
          200: 'rgb(var(--ds-primary-color-200))',
          300: 'rgb(var(--ds-primary-color-300))',
          400: 'rgb(var(--ds-primary-color-400))',
          500: 'rgb(var(--ds-primary-color-500))',
          600: 'rgb(var(--ds-primary-color-600))',
          700: 'rgb(var(--ds-primary-color-700))',
          800: 'rgb(var(--ds-primary-color-800))',
          900: 'rgb(var(--ds-primary-color-900))',
        },
        secondary: {
          DEFAULT: 'rgb(var(--ds-secondary-color))',
          50: 'rgb(var(--ds-secondary-color-50))',
          100: 'rgb(var(--ds-secondary-color-100))',
          200: 'rgb(var(--ds-secondary-color-200))',
          300: 'rgb(var(--ds-secondary-color-300))',
          400: 'rgb(var(--ds-secondary-color-400))',
          500: 'rgb(var(--ds-secondary-color-500))',
          600: 'rgb(var(--ds-secondary-color-600))',
          700: 'rgb(var(--ds-secondary-color-700))',
          800: 'rgb(var(--ds-secondary-color-800))',
          900: 'rgb(var(--ds-secondary-color-900))',
        },
        accent: {
          DEFAULT: 'rgb(var(--ds-accent-color))',
          50: 'rgb(var(--ds-accent-color-50))',
          100: 'rgb(var(--ds-accent-color-100))',
          200: 'rgb(var(--ds-accent-color-200))',
          300: 'rgb(var(--ds-accent-color-300))',
          400: 'rgb(var(--ds-accent-color-400))',
          500: 'rgb(var(--ds-accent-color-500))',
          600: 'rgb(var(--ds-accent-color-600))',
          700: 'rgb(var(--ds-accent-color-700))',
          800: 'rgb(var(--ds-accent-color-800))',
          900: 'rgb(var(--ds-accent-color-900))',
        },
        gray: {
          DEFAULT: 'rgb(var(--ds-gray-color))',
          50: 'rgb(var(--ds-gray-color-50))',
          100: 'rgb(var(--ds-gray-color-100))',
          200: 'rgb(var(--ds-gray-color-200))',
          300: 'rgb(var(--ds-gray-color-300))',
          400: 'rgb(var(--ds-gray-color-400))',
          500: 'rgb(var(--ds-gray-color-500))',
          600: 'rgb(var(--ds-gray-color-600))',
          700: 'rgb(var(--ds-gray-color-700))',
          800: 'rgb(var(--ds-gray-color-800))',
          900: 'rgb(var(--ds-gray-color-900))',
        },
        background: 'rgb(var(--ds-background-color-light))',
        'primary-text': 'rgb(var(--ds-primary-text-color-light))',
        'secondary-text': 'rgb(var(--ds-secondary-text-color-light))',
        border: 'rgb(var(--ds-border-color-light))',
        'highlight-bg': 'rgb(var(--ds-highlight-bg-light))',
        'highlight-text': 'rgb(var(--ds-highlight-text-color-light))',
        error: 'rgb(var(--ds-error-color))',
        success: 'rgb(var(--ds-success-color))',
        info: 'rgb(var(--ds-info-color))',
        warning: 'rgb(var(--ds-warning-color))',
        white: 'rgb(var(--ds-white-color))',
        black: 'rgb(var(--ds-black-color))',
      },
      fontFamily: {
        base: 'var(--ds-font-family-base)',
      },
      fontSize: {
        base: 'var(--ds-font-size-base)',
      },
      fontWeight: {
        bold: 'var(--ds-font-weight-bold)',
      },
      lineHeight: {
        base: 'var(--ds-line-height)',
      },
      spacing: {
        xxs: 'var(--ds-spacing-xxs)',
        xs: 'var(--ds-spacing-xs)',
        sm: 'var(--ds-spacing-sm)',
        md: 'var(--ds-spacing-md)',
        lg: 'var(--ds-spacing-lg)',
        xl: 'var(--ds-spacing-xl)',
        xxl: 'var(--ds-spacing-xxl)',
        xxxl: 'var(--ds-spacing-xxxl)',
      },
      borderRadius: {
        base: 'var(--ds-border-radius-base)',
        sm: 'var(--ds-border-radius-sm)',
        lg: 'var(--ds-border-radius-lg)',
        xl: 'var(--ds-border-radius-xl)',
        full: 'var(--ds-border-radius-full)',
      },
      boxShadow: {
        sm: 'var(--ds-box-shadow-sm)',
        md: 'var(--ds-box-shadow-md)',
        lg: 'var(--ds-box-shadow-lg)',
        xl: 'var(--ds-box-shadow-xl)',
      },
    },
  },
  plugins: [],
};
