/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--primary-color))',
          50: 'rgb(var(--primary-color-50))',
          100: 'rgb(var(--primary-color-100))',
          200: 'rgb(var(--primary-color-200))',
          300: 'rgb(var(--primary-color-300))',
          400: 'rgb(var(--primary-color-400))',
          500: 'rgb(var(--primary-color-500))',
          600: 'rgb(var(--primary-color-600))',
          700: 'rgb(var(--primary-color-700))',
          800: 'rgb(var(--primary-color-800))',
          900: 'rgb(var(--primary-color-900))',
        },
        secondary: {
          DEFAULT: 'rgb(var(--secondary-color))',
          50: 'rgb(var(--secondary-color-50))',
          100: 'rgb(var(--secondary-color-100))',
          200: 'rgb(var(--secondary-color-200))',
          300: 'rgb(var(--secondary-color-300))',
          400: 'rgb(var(--secondary-color-400))',
          500: 'rgb(var(--secondary-color-500))',
          600: 'rgb(var(--secondary-color-600))',
          700: 'rgb(var(--secondary-color-700))',
          800: 'rgb(var(--secondary-color-800))',
          900: 'rgb(var(--secondary-color-900))',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent-color))',
          50: 'rgb(var(--accent-color-50))',
          100: 'rgb(var(--accent-color-100))',
          200: 'rgb(var(--accent-color-200))',
          300: 'rgb(var(--accent-color-300))',
          400: 'rgb(var(--accent-color-400))',
          500: 'rgb(var(--accent-color-500))',
          600: 'rgb(var(--accent-color-600))',
          700: 'rgb(var(--accent-color-700))',
          800: 'rgb(var(--accent-color-800))',
          900: 'rgb(var(--accent-color-900))',
        },
        gray: {
          DEFAULT: 'rgb(var(--gray-color))',
          50: 'rgb(var(--gray-color-50))',
          100: 'rgb(var(--gray-color-100))',
          200: 'rgb(var(--gray-color-200))',
          300: 'rgb(var(--gray-color-300))',
          400: 'rgb(var(--gray-color-400))',
          500: 'rgb(var(--gray-color-500))',
          600: 'rgb(var(--gray-color-600))',
          700: 'rgb(var(--gray-color-700))',
          800: 'rgb(var(--gray-color-800))',
          900: 'rgb(var(--gray-color-900))',
        },
        background: 'rgb(var(--background-color-light))',
        'primary-text': 'rgb(var(--primary-text-color-light))',
        'secondary-text': 'rgb(var(--secondary-text-color-light))',
        border: 'rgb(var(--border-color-light))',
        'highlight-bg': 'rgb(var(--highlight-bg-light))',
        'highlight-text': 'rgb(var(--highlight-text-color-light))',
        error: 'rgb(var(--error-color))',
        success: 'rgb(var(--success-color))',
        info: 'rgb(var(--info-color))',
        warning: 'rgb(var(--warning-color))',
        white: 'rgb(var(--white-color))',
        black: 'rgb(var(--black-color))',
      },
      fontFamily: {
        base: 'var(--font-family-base)',
      },
      fontSize: {
        base: 'var(--font-size-base)',
      },
      fontWeight: {
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        base: 'var(--line-height)',
      },
      spacing: {
        xxs: 'var(--spacing-xxs)',
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
        xxl: 'var(--spacing-xxl)',
        xxxl: 'var(--spacing-xxxl)',
      },
      borderRadius: {
        base: 'var(--border-radius-base)',
        sm: 'var(--border-radius-sm)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        full: 'var(--border-radius-full)',
      },
      boxShadow: {
        sm: 'var(--box-shadow-sm)',
        md: 'var(--box-shadow-md)',
        lg: 'var(--box-shadow-lg)',
        xl: 'var(--box-shadow-xl)',
      },
    },
  },
  plugins: [],
};
