export const countries = [
  { id: 1, name: 'Colombia' },
  { id: 2, name: 'Argentina' },
  { id: 3, name: 'Chile' },
  { id: 4, name: 'Perú' },
  { id: 5, name: 'México' },
  { id: 6, name: 'Uruguay' },
  { id: 7, name: 'Ecuador' },
  { id: 8, name: 'Bolivia' },
  { id: 9, name: 'Paraguay' },
  { id: 10, name: 'Costa Rica' },
  { id: 11, name: 'España' },
  { id: 12, name: 'Reino Unido' },
  { id: 13, name: 'Francia' },
  { id: 14, name: 'Italia' },
  { id: 15, name: 'Alemania' },
  { id: 16, name: 'Países Bajos' },
  { id: 17, name: 'Austria' },
  { id: 18, name: 'Grecia' },
  { id: 19, name: 'Portugal' },
  { id: 20, name: 'Japón' },
  { id: 21, name: 'China' },
  { id: 22, name: 'Corea del Sur' },
  { id: 23, name: 'Tailandia' },
  { id: 24, name: 'India' },
  { id: 25, name: 'Singapur' },
  { id: 26, name: 'Malasia' },
  { id: 27, name: 'Emiratos Árabes Unidos' },
  { id: 28, name: 'Hong Kong' },
  { id: 29, name: 'Estados Unidos' },
];
