name: Docker Ultra-Hotels

on:
  push:
    branches:: ['main']
  pull_request:
    branches:: ['main']

jobs:
  deploy:
    name: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t darcdev/ultra.hotels.web:latest .
          docker tag darcdev/ultra.hotels.web:latest darcdev/ultra.hotels.web:latest

      - name: Publish Docker image
        run: |
          docker push darcdev/ultra.hotels.web:latest

      - name: Service Auth Azure
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: 'ultra-hotels'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'darcdev/ultra.hotels.web:latest'